version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: casa-nova-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: casa_nova
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: